import type { StationWithDJ } from "@ownradio/shared";

export const OWNRADIO_SLUG = "ownradio";

export const OWNRADIO_FALLBACK: StationWithDJ = {
  id: "mock-ownradio",
  name: "OwnRadio",
  slug: OWNRADIO_SLUG,
  description: "AI-powered radio by PlayGen",
  streamUrl:
    "https://api.playgen.site/stream/324135e0-151a-4cb7-bff3-bca7a099a68c/playlist.m3u8",
  metadataUrl: "",
  genre: "OPM",
  artworkUrl: "",
  isLive: true,
  createdAt: "",
  updatedAt: "",
  dj: {
    id: "dj-alex",
    stationId: "mock-ownradio",
    name: "DJ Alex",
    bio: "AI-powered DJ spinning the freshest tracks.",
    avatarUrl: "",
    createdAt: "",
  },
  listenerCount: 0,
  currentSong: null,
};

export const MOCK_STATIONS: StationWithDJ[] = [
  // ── LIVE ──────────────────────────────────────────────────────────────
  {
    id: "mock-rock",
    name: "Rock Haven",
    slug: "rock-haven",
    description: "Classic and modern rock — the riffs never stop.",
    streamUrl: "mock",
    metadataUrl: "",
    genre: "Rock",
    artworkUrl: "",
    isLive: true,
    createdAt: "",
    updatedAt: "",
    dj: {
      id: "dj-axel",
      stationId: "mock-rock",
      name: "DJ Axel",
      bio: "Rock aficionado spinning the best riffs since 2010.",
      avatarUrl: "",
      createdAt: "",
    },
    listenerCount: 1243,
    currentSong: {
      id: "s-r1",
      stationId: "mock-rock",
      title: "Bohemian Rhapsody",
      artist: "Queen",
      albumCoverUrl: null,
      playedAt: "",
      duration: 354,
    },
  },
  {
    id: "mock-hiphop",
    name: "Beat Street",
    slug: "beat-street",
    description: "Hip-hop and R&B vibes all day, every day.",
    streamUrl: "mock",
    metadataUrl: "",
    genre: "Hip-Hop",
    artworkUrl: "",
    isLive: true,
    createdAt: "",
    updatedAt: "",
    dj: {
      id: "dj-mcflow",
      stationId: "mock-hiphop",
      name: "MC Flow",
      bio: "Keeping the beat alive since day one.",
      avatarUrl: "",
      createdAt: "",
    },
    listenerCount: 892,
    currentSong: {
      id: "s-h1",
      stationId: "mock-hiphop",
      title: "Lose Yourself",
      artist: "Eminem",
      albumCoverUrl: null,
      playedAt: "",
      duration: 326,
    },
  },
  {
    id: "mock-lofi",
    name: "Chill Waves",
    slug: "chill-waves",
    description: "Lo-fi beats to study, relax, and drift away.",
    streamUrl: "mock",
    metadataUrl: "",
    genre: "Lo-Fi",
    artworkUrl: "",
    isLive: true,
    createdAt: "",
    updatedAt: "",
    dj: {
      id: "dj-luna",
      stationId: "mock-lofi",
      name: "DJ Luna",
      bio: "Late-night lo-fi sessions — coffee optional.",
      avatarUrl: "",
      createdAt: "",
    },
    listenerCount: 2107,
    currentSong: {
      id: "s-l1",
      stationId: "mock-lofi",
      title: "Snowfall",
      artist: "Øneheart & reidenshi",
      albumCoverUrl: null,
      playedAt: "",
      duration: 186,
    },
  },
  {
    id: "mock-pop",
    name: "Pop Spectrum",
    slug: "pop-spectrum",
    description: "The hottest pop hits, non-stop.",
    streamUrl: "mock",
    metadataUrl: "",
    genre: "Pop",
    artworkUrl: "",
    isLive: true,
    createdAt: "",
    updatedAt: "",
    dj: {
      id: "dj-aria",
      stationId: "mock-pop",
      name: "DJ Aria",
      bio: "Your daily dose of feel-good pop energy.",
      avatarUrl: "",
      createdAt: "",
    },
    listenerCount: 3418,
    currentSong: {
      id: "s-p1",
      stationId: "mock-pop",
      title: "As It Was",
      artist: "Harry Styles",
      albumCoverUrl: null,
      playedAt: "",
      duration: 167,
    },
  },
  // ── COMING SOON ───────────────────────────────────────────────────────
  {
    id: "mock-opm",
    name: "OPM Vibes",
    slug: "opm-vibes",
    description: "The best of Original Pilipino Music.",
    streamUrl: "",
    metadataUrl: "",
    genre: "OPM",
    artworkUrl: "",
    isLive: false,
    createdAt: "",
    updatedAt: "",
    dj: {
      id: "dj-kiko",
      stationId: "mock-opm",
      name: "DJ Kiko",
      bio: "Bringing OPM to the world, one song at a time.",
      avatarUrl: "",
      createdAt: "",
    },
    listenerCount: 0,
    currentSong: {
      id: "s-o1",
      stationId: "mock-opm",
      title: "Ligaya",
      artist: "Eraserheads",
      albumCoverUrl: null,
      playedAt: "",
      duration: 205,
    },
  },
  {
    id: "mock-jazz",
    name: "Neon Jazz",
    slug: "neon-jazz",
    description: "Late-night jazz with a neon-lit soul.",
    streamUrl: "",
    metadataUrl: "",
    genre: "Jazz",
    artworkUrl: "",
    isLive: false,
    createdAt: "",
    updatedAt: "",
    dj: {
      id: "dj-miles",
      stationId: "mock-jazz",
      name: "DJ Miles",
      bio: "Jazz purist with a love for midnight sessions.",
      avatarUrl: "",
      createdAt: "",
    },
    listenerCount: 0,
    currentSong: {
      id: "s-j1",
      stationId: "mock-jazz",
      title: "So What",
      artist: "Miles Davis",
      albumCoverUrl: null,
      playedAt: "",
      duration: 556,
    },
  },
  {
    id: "mock-edm",
    name: "Bass Drop",
    slug: "bass-drop",
    description: "Electronic beats that shake the floor.",
    streamUrl: "",
    metadataUrl: "",
    genre: "Electronic",
    artworkUrl: "",
    isLive: false,
    createdAt: "",
    updatedAt: "",
    dj: {
      id: "dj-zara",
      stationId: "mock-edm",
      name: "DJ Zara",
      bio: "From deep house to hard bass — Zara drops it all.",
      avatarUrl: "",
      createdAt: "",
    },
    listenerCount: 0,
    currentSong: {
      id: "s-e1",
      stationId: "mock-edm",
      title: "Levels",
      artist: "Avicii",
      albumCoverUrl: null,
      playedAt: "",
      duration: 199,
    },
  },
  {
    id: "mock-rnb",
    name: "Smooth R&B",
    slug: "smooth-rnb",
    description: "Soulful R&B for every mood.",
    streamUrl: "",
    metadataUrl: "",
    genre: "R&B",
    artworkUrl: "",
    isLive: false,
    createdAt: "",
    updatedAt: "",
    dj: {
      id: "dj-nova",
      stationId: "mock-rnb",
      name: "DJ Nova",
      bio: "Smooth grooves and soulful sounds, always.",
      avatarUrl: "",
      createdAt: "",
    },
    listenerCount: 0,
    currentSong: {
      id: "s-rb1",
      stationId: "mock-rnb",
      title: "No Ordinary Love",
      artist: "Sade",
      albumCoverUrl: null,
      playedAt: "",
      duration: 264,
    },
  },
];

/** Merge API stations with mock fallbacks (API stations take priority by slug). */
export function mergeWithMocks(apiStations: StationWithDJ[]): StationWithDJ[] {
  const allMocks = [OWNRADIO_FALLBACK, ...MOCK_STATIONS];
  const apiSlugs = new Set(apiStations.map((s) => s.slug));
  const mockPad = allMocks.filter((s) => !apiSlugs.has(s.slug));
  return [...apiStations, ...mockPad];
}
