import type { StationWithDJ } from "@ownradio/shared";

export const MOCK_STATIONS: StationWithDJ[] = [
  {
    id: "mock-station-1",
    name: "Rock Haven",
    slug: "rock-haven",
    description: "Pure rock energy 24/7 — from classic riffs to modern anthems.",
    streamUrl: "https://stream.example.com/rock-haven",
    metadataUrl: "https://stream.example.com/rock-haven/metadata",
    genre: "Rock",
    artworkUrl: "",
    isLive: true,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    listenerCount: 42,
    dj: {
      id: "mock-dj-1",
      stationId: "mock-station-1",
      name: "Max Thunder",
      bio: "Rock veteran with 15 years on the decks. Loud, proud, and never boring.",
      avatarUrl: "",
      createdAt: "2024-01-01T00:00:00.000Z",
    },
    currentSong: {
      id: "mock-song-1",
      stationId: "mock-station-1",
      title: "Thunder Road",
      artist: "The Rock Collective",
      albumCoverUrl: null,
      playedAt: new Date().toISOString(),
      duration: 240,
    },
  },
  {
    id: "mock-station-2",
    name: "Beat Lounge",
    slug: "beat-lounge",
    description: "Hip-hop and R&B vibes to keep your head nodding all day long.",
    streamUrl: "https://stream.example.com/beat-lounge",
    metadataUrl: "https://stream.example.com/beat-lounge/metadata",
    genre: "Hip-Hop / R&B",
    artworkUrl: "",
    isLive: true,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    listenerCount: 67,
    dj: {
      id: "mock-dj-2",
      stationId: "mock-station-2",
      name: "DJ Smooth",
      bio: "From the streets to the speakers — DJ Smooth curates the smoothest beats in town.",
      avatarUrl: "",
      createdAt: "2024-01-01T00:00:00.000Z",
    },
    currentSong: {
      id: "mock-song-2",
      stationId: "mock-station-2",
      title: "Midnight Groove",
      artist: "Smooth Collective",
      albumCoverUrl: null,
      playedAt: new Date().toISOString(),
      duration: 210,
    },
  },
  {
    id: "mock-station-3",
    name: "Chill Waves",
    slug: "chill-waves",
    description: "Lo-fi beats and ambient soundscapes for focus, study, and relaxation.",
    streamUrl: "https://stream.example.com/chill-waves",
    metadataUrl: "https://stream.example.com/chill-waves/metadata",
    genre: "Lo-Fi / Ambient",
    artworkUrl: "",
    isLive: true,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    listenerCount: 29,
    dj: {
      id: "mock-dj-3",
      stationId: "mock-station-3",
      name: "Luna",
      bio: "Luna crafts sonic escapes that blur the line between music and atmosphere.",
      avatarUrl: "",
      createdAt: "2024-01-01T00:00:00.000Z",
    },
    currentSong: {
      id: "mock-song-3",
      stationId: "mock-station-3",
      title: "Rainy Afternoon",
      artist: "Luna & The Fog",
      albumCoverUrl: null,
      playedAt: new Date().toISOString(),
      duration: 180,
    },
  },
  {
    id: "mock-station-4",
    name: "Pinoy Hits",
    slug: "pinoy-hits",
    description: "The best OPM — from timeless classics to today's chart-toppers.",
    streamUrl: "https://stream.example.com/pinoy-hits",
    metadataUrl: "https://stream.example.com/pinoy-hits/metadata",
    genre: "OPM",
    artworkUrl: "",
    isLive: true,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-01-01T00:00:00.000Z",
    listenerCount: 55,
    dj: {
      id: "mock-dj-4",
      stationId: "mock-station-4",
      name: "DJ Kuya",
      bio: "Keeping OPM alive and loud. DJ Kuya is your kuya on the airwaves.",
      avatarUrl: "",
      createdAt: "2024-01-01T00:00:00.000Z",
    },
    currentSong: {
      id: "mock-song-4",
      stationId: "mock-station-4",
      title: "Hanap-Hanap",
      artist: "Banda Pilipino",
      albumCoverUrl: null,
      playedAt: new Date().toISOString(),
      duration: 225,
    },
  },
];
